{% set version = "2.0.1" %}
{% set name = "cykhash" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4794bc9f549114d8cf1d856d9f64e08ff5f246bf043cf369fdb414e9ceb97f7

build:
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.28
    - setuptools
  run:
    - python

test:
  imports:
    - cykhash

about:
  home: https://github.com/realead/cykhash
  license: MIT
  license_file: LICENSE
  summary: cython wrapper for khash-sets/maps, efficient implementation of `isin` and `unique`

extra:
  recipe-maintainers:
    - htenkanen
    - realead
